CREATE INDEX "idx_academic_attitude_logs_student_id" ON "academic_attitude_logs" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_academic_attitude_logs_grade_id" ON "academic_attitude_logs" USING btree ("course_grade_id");--> statement-breakpoint
CREATE INDEX "idx_academic_data_student_id" ON "academic_data" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_academic_documents_student_id" ON "academic_documents" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_announcements_target_cohort" ON "announcements" USING btree ("target_cohort");--> statement-breakpoint
CREATE INDEX "idx_attendance_records_session_id" ON "attendance_records" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "idx_attendance_records_student_id" ON "attendance_records" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_attendance_sessions_cohort" ON "attendance_sessions" USING btree ("cohort");--> statement-breakpoint
CREATE INDEX "idx_attendance_sessions_session_date" ON "attendance_sessions" USING btree ("session_date");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_user_id" ON "audit_logs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_entity" ON "audit_logs" USING btree ("entity","entity_id");--> statement-breakpoint
CREATE INDEX "idx_class_schedules_cohort" ON "class_schedules" USING btree ("cohort");--> statement-breakpoint
CREATE INDEX "idx_class_schedules_dosen_id" ON "class_schedules" USING btree ("dosen_id");--> statement-breakpoint
CREATE INDEX "idx_class_schedules_calendar_id" ON "class_schedules" USING btree ("calendar_id");--> statement-breakpoint
CREATE INDEX "idx_counseling_logs_student_id" ON "counseling_logs" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_course_grade_docs_student_id" ON "course_grade_documents" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_course_grade_docs_grade_id" ON "course_grade_documents" USING btree ("course_grade_id");--> statement-breakpoint
CREATE INDEX "idx_course_grades_student_id" ON "course_grades" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_course_grades_course_id" ON "course_grades" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "idx_crm_data_student_id" ON "crm_data" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_crm_documents_student_id" ON "crm_documents" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_crm_logs_student_id" ON "crm_logs" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_departure_assessment_notes_assessment_id" ON "departure_assessment_notes" USING btree ("assessment_id");--> statement-breakpoint
CREATE INDEX "idx_departure_assessments_student_id" ON "departure_assessments" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_duty_schedules_cohort" ON "duty_schedules" USING btree ("cohort");--> statement-breakpoint
CREATE INDEX "idx_duty_schedules_calendar_id" ON "duty_schedules" USING btree ("calendar_id");--> statement-breakpoint
CREATE INDEX "idx_entrepreneurship_records_student_id" ON "entrepreneurship_records" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_entrepreneurship_records_grade_id" ON "entrepreneurship_records" USING btree ("course_grade_id");--> statement-breakpoint
CREATE INDEX "idx_fee_share_recipients_student_id" ON "fee_share_recipients" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_files_student_id" ON "files" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_files_panel_key" ON "files" USING btree ("panel","document_key");--> statement-breakpoint
CREATE INDEX "idx_final_decision_student_id" ON "final_decision" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_finance_custom_fields_student_id" ON "finance_custom_fields" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_finance_data_student_id" ON "finance_data" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_finance_documents_student_id" ON "finance_documents" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_finance_semester_installments_sem_id" ON "finance_semester_installments" USING btree ("semester_id");--> statement-breakpoint
CREATE INDEX "idx_finance_semesters_student_id" ON "finance_semesters" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_finance_talangan_installments_student_id" ON "finance_talangan_installments" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_internal_notes_student_id" ON "internal_notes" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_internship_data_student_id" ON "internship_data" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_internship_documents_student_id" ON "internship_documents" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_internship_monitoring_sched_student_id" ON "internship_monitoring_schedule" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_ods_attendance_records_student_id" ON "ods_attendance_records" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_ods_attendance_records_date" ON "ods_attendance_records" USING btree ("date");--> statement-breakpoint
CREATE INDEX "idx_overseas_checklists_student_id" ON "overseas_program_checklists" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_pa_data_student_id" ON "pa_data" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_pa_documents_student_id" ON "pa_documents" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_pa_hafalan_sessions_student_id" ON "pa_hafalan_sessions" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_pa_interview_logs_student_id" ON "pa_interview_logs" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_pa_student_notes_student_id" ON "pa_student_notes" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_pa_tripartite_logs_student_id" ON "pa_tripartite_logs" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_pmb_data_student_id" ON "pmb_data" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_pmb_documents_student_id" ON "pmb_documents" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_pmb_fee_disbursements_student_id" ON "pmb_fee_disbursements" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_pmb_form_responses_student_id" ON "pmb_form_responses" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_pmb_form_tokens_token" ON "pmb_form_tokens" USING btree ("token");--> statement-breakpoint
CREATE INDEX "idx_pmb_payment_plan_student_id" ON "pmb_payment_plan" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_post_internship_docs_student_id" ON "post_internship_docs" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_practices_budget_requests_dosen_id" ON "practices_budget_requests" USING btree ("dosen_id");--> statement-breakpoint
CREATE INDEX "idx_practices_budget_requests_course_id" ON "practices_budget_requests" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "idx_practices_material_reports_request_id" ON "practices_material_reports" USING btree ("budget_request_id");--> statement-breakpoint
CREATE INDEX "idx_practicum_schedules_cohort" ON "practicum_schedules" USING btree ("cohort");--> statement-breakpoint
CREATE INDEX "idx_practicum_schedules_dosen_id" ON "practicum_schedules" USING btree ("dosen_id");--> statement-breakpoint
CREATE INDEX "idx_practicum_schedules_calendar_id" ON "practicum_schedules" USING btree ("calendar_id");--> statement-breakpoint
CREATE INDEX "idx_pramagang_attendance_records_student_id" ON "pramagang_attendance_records" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_pramagang_attendance_records_date" ON "pramagang_attendance_records" USING btree ("date");--> statement-breakpoint
CREATE INDEX "idx_student_health_student_id" ON "student_health" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_student_parents_student_id" ON "student_parents" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_students_is_archived_updated_at" ON "students" USING btree ("is_archived","updated_at","id");--> statement-breakpoint
CREATE INDEX "idx_students_cohort_archived" ON "students" USING btree ("cohort","is_archived");--> statement-breakpoint
CREATE INDEX "idx_students_status_archived" ON "students" USING btree ("overall_status","is_archived");--> statement-breakpoint
CREATE INDEX "idx_students_name" ON "students" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_students_pa_id" ON "students" USING btree ("pa_id");--> statement-breakpoint
CREATE INDEX "idx_vocab_logs_student_id" ON "vocab_logs" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_weekly_events_student_id" ON "weekly_events" USING btree ("student_id");